### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by shrek69420lol** [epiceuropean/Better-Void-Heart#1]
its not showing up in the mod list and not working at all

**Comment by epiceuropean** [comment]
I just checked and it's in the modlinks and shows up in Scarab for me. I just uninstalled an reinstalled it through there, and it seems to work on my end. 

I heard there was a recent version of Scarab that had some bugs. Can you update Scarab and check again? Let me know if that helps or if you still have trouble!

**Comment by epiceuropean** [comment]
I think everything works right now, so I'm going to close this issue. Please reply if that's not the case.
